In [1]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import KNNImputer, SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import recall_score, classification_report
import numpy as np
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.inspection import permutation_importance
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
import warnings
from pytorch_tabnet.tab_model import TabNetClassifier

In [2]:
df = pd.read_csv('foods_health_scores_allergens.csv')
df

,product_name,brands,categories,ingredients,nutriscore_grade,nova_group,ecoscore_grade,allergens,energy_kcal,fat_100g,...,proteins_100g,salt_100g,sodium_100g,contains_gluten,contains_dairy,contains_nuts,contains_soy,contains_eggs,contains_fish,food_type
0,Sidi Ali,سيدي علي,"en:beverages-and-beverages-preparations, en:be...",OBD1 999 999 1112606 266963207 mb,A,NaN,NOT-APPLICABLE,NaN,0.0,0.0,...,0.0,0.000000,0.000000,False,False,False,False,False,False,Branded/Packaged
1,Perly,Perly,"en:dairies, en:fermented-foods, en:fermented-m...","milk cream, cream, sugar, banana, bacteria",UNKNOWN,3.0,B,"en:banana, en:milk",97.0,3.0,...,8.0,NaN,NaN,False,True,False,False,False,False,Branded/Packaged
2,Sidi Ali,Sidi Ali,"en:beverages-and-beverages-preparations, en:be...","Sodium, Calcium, Magnésium, Potassium, Bicarbo...",A,1.0,NOT-APPLICABLE,NaN,NaN,NaN,...,NaN,0.065000,0.026000,False,False,False,False,False,False,Branded/Packaged
3,Eau minérale naturelle,sidi ali,"en:beverages-and-beverages-preparations, en:be...",100% mineral water,A,1.0,NOT-APPLICABLE,NaN,NaN,NaN,...,NaN,0.065000,0.026000,False,False,False,False,False,False,Branded/Packaged
4,اكوافينا,AQUAFINA,"en:beverages-and-beverages-preparations, en:be...",ouverture et avant le : Voir bouteille. après ...,A,NaN,NOT-APPLICABLE,NaN,0.0,0.0,...,0.0,0.000508,0.000203,False,False,False,False,False,False,Branded/Packaged
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4992,Crème fraîche gastronomique,Président,"en:dairies, en:fermented-foods, en:fermented-m...","_Crème_ (origine France), _ferments lactiques_",D,3.0,A,en:milk,291.0,30.0,...,2.3,0.070000,0.028000,False,True,False,False,False,False,Branded/Packaged
4993,Noix de cajou grillées sans sel,Maître Prunille,"en:plant-based-foods-and-beverages, en:plant-b...",Noix de cajou,B,1.0,E,en:nuts,621.0,47.0,...,21.0,0.020000,0.008000,False,False,True,False,False,False,Branded/Packaged
4994,Cacao puro en polvo desgrasado,Valor,"en:cocoa-and-its-products, en:cocoa-and-chocol...","Cacao desgrasado en polvo, correctores de acid...",C,1.0,F,NaN,375.0,16.0,...,26.0,0.030000,0.012000,False,False,False,False,False,False,Branded/Packaged
4995,Sablés Myrtilles Germes de riz,Gerblé,"en:snacks, en:sweet-snacks, en:biscuits-and-cakes","Farine de blé 58,2%, huile de colza, sucre de ...",A,4.0,C,"en:gluten, en:milk",54.0,2.0,...,0.9,0.050000,0.020000,True,True,False,False,False,False,Branded/Packaged
4996,Céréales Extra Pepites Kellogg's Chocolat au lait,Kellogg's,"en:plant-based-foods-and-beverages, en:plant-b...","Flocons d'AVOINE(47%), Sucre, Huile de palme, ...",E,4.0,E,"en:gluten, en:milk, en:soybeans",484.0,22.0,...,7.0,0.680000,0.272000,True,True,False,True,False,False,Branded/Packaged

In [3]:
df["food_type"].value_counts()

food_type
Branded/Packaged    4997
Name: count, dtype: int64

In [4]:
df = df.drop(['product_name', 'brands', 'categories', 'ingredients', 'allergens', 'food_type'], axis = 1)

In [5]:
cols = [
    'contains_gluten',
    'contains_dairy',
    'contains_nuts',
    'contains_soy',
    'contains_eggs',
    'contains_fish'
]

df['Y'] = df[cols].any(axis=1)

In [6]:
df['Y'] = df['Y'].astype(int)

In [7]:
df["Y"]

0       0
1       1
2       0
3       0
4       0
       ..
4992    1
4993    1
4994    0
4995    1
4996    1
Name: Y, Length: 4997, dtype: int64

In [8]:
df = df.drop(cols, axis = 1)

In [9]:
df

,nutriscore_grade,nova_group,ecoscore_grade,energy_kcal,fat_100g,saturated_fat_100g,carbs_100g,sugars_100g,fiber_100g,proteins_100g,salt_100g,sodium_100g,Y
0,A,NaN,NOT-APPLICABLE,0.0,0.0,0.0,4.2,1.4,0.0,0.0,0.000000,0.000000,0
1,UNKNOWN,3.0,B,97.0,3.0,NaN,9.4,NaN,NaN,8.0,NaN,NaN,1
2,A,1.0,NOT-APPLICABLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.065000,0.026000,0
3,A,1.0,NOT-APPLICABLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.065000,0.026000,0
4,A,NaN,NOT-APPLICABLE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000508,0.000203,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4992,D,3.0,A,291.0,30.0,22.0,2.9,2.9,NaN,2.3,0.070000,0.028000,1
4993,B,1.0,E,621.0,47.0,8.7,25.0,6.2,4.5,21.0,0.020000,0.008000,1
4994,C,1.0,F,375.0,16.0,10.0,16.0,0.7,32.0,26.0,0.030000,0.012000,0
4995,A,4.0,C,54.0,2.0,0.2,7.9,1.9,0.5,0.9,0.050000,0.020000,1
4996,E,4.0,E,484.0,22.0,10.0,62.0,25.0,4.9,7.0,0.680000,0.272000,1

In [10]:
df.columns

Index(['nutriscore_grade', 'nova_group', 'ecoscore_grade', 'energy_kcal',
       'fat_100g', 'saturated_fat_100g', 'carbs_100g', 'sugars_100g',
       'fiber_100g', 'proteins_100g', 'salt_100g', 'sodium_100g', 'Y'],
      dtype='str')

In [11]:
y = df["Y"]
X = df.drop("Y", axis = 1)

In [12]:
y.value_counts(normalize = True)

Y
1    0.621573
0    0.378427
Name: proportion, dtype: float64

In [13]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,        
    random_state=5831,      
    stratify=y           
)

In [33]:
baseline_recall = (y_test == 1).mean()
print("Baseline recall:", baseline_recall)

Baseline recall: 0.622

In [14]:
# ---- define your columns ----
num_cols = ['energy_kcal','fat_100g', 'saturated_fat_100g', 'carbs_100g', 'sugars_100g','fiber_100g', 'proteins_100g', 'salt_100g', 'sodium_100g']     
cat_cols = ['nutriscore_grade', 'nova_group', 'ecoscore_grade']     

# ---- numeric pipeline ----
num_pipeline = Pipeline([
    ("imputer", KNNImputer(n_neighbors=5)),
    ("scaler", StandardScaler())
])

# ---- categorical pipeline ----
cat_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

# ---- combine ----
preprocess = ColumnTransformer([
    ("num", num_pipeline, num_cols),
    ("cat", cat_pipeline, cat_cols)
])

# ---- full pipeline ----
pipe = Pipeline([
    ("preprocess", preprocess),
    ("lda", LinearDiscriminantAnalysis())
])

In [15]:
pipe.fit(X_train, y_train)
y_pred = pipe.predict(X_test)

In [16]:
recall = recall_score(y_test, y_pred, pos_label=1)
print("Recall:", recall)

Recall: 0.9356913183279743

In [17]:
result = permutation_importance(
    pipe, X_test, y_test,
    n_repeats=10,
    random_state=5831,
    n_jobs=-1
)

importance = pd.DataFrame({
    "feature": X_test.columns,
    "importance": result.importances_mean
}).sort_values(by="importance", ascending=False)

print(importance.head(10))

               feature  importance
0     nutriscore_grade      0.0633
2       ecoscore_grade      0.0580
1           nova_group      0.0323
3          energy_kcal      0.0314
9        proteins_100g      0.0276
4             fat_100g      0.0185
5   saturated_fat_100g      0.0134
7          sugars_100g      0.0084
11         sodium_100g      0.0034
8           fiber_100g      0.0013

In [18]:
num_pipeline = Pipeline([
    ("imputer", KNNImputer(n_neighbors=5)),
    ("scaler", StandardScaler())
])

cat_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore", sparse_output=False))
])

preprocess = ColumnTransformer([
    ("num", num_pipeline, num_cols),
    ("cat", cat_pipeline, cat_cols)
])

pipe = Pipeline([
    ("preprocess", preprocess),
    ("qda", QuadraticDiscriminantAnalysis(reg_param=0.1))
])

In [19]:
pipe.fit(X_train, y_train)
y_pred = pipe.predict(X_test)

In [20]:
recall = recall_score(y_test, y_pred, pos_label=1)
print("Recall:", recall)

Recall: 0.9758842443729904

In [21]:
result = permutation_importance(
    pipe, X_test, y_test,
    n_repeats=10,
    random_state=5831,
    n_jobs=-1
)

importance = pd.DataFrame({
    "feature": X_test.columns,
    "importance": result.importances_mean
}).sort_values(by="importance", ascending=False)

print(importance.head(10))

               feature  importance
2       ecoscore_grade      0.0465
3          energy_kcal      0.0141
0     nutriscore_grade      0.0121
4             fat_100g      0.0091
5   saturated_fat_100g      0.0053
1           nova_group      0.0025
11         sodium_100g      0.0022
8           fiber_100g      0.0018
9        proteins_100g      0.0016
7          sugars_100g      0.0013

In [22]:
num_pipeline = Pipeline([
    ("imputer", KNNImputer(n_neighbors=5)),
    ("scaler", StandardScaler())
])

cat_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore", drop="first", sparse_output=False))
])

preprocess = ColumnTransformer([
    ("num", num_pipeline, num_cols),
    ("cat", cat_pipeline, cat_cols)
])

pipe = Pipeline([
    ("preprocess", preprocess),
    ("lda", LinearDiscriminantAnalysis(solver="lsqr", shrinkage="auto"))
])

In [23]:
pipe.fit(X_train, y_train)
y_pred = pipe.predict(X_test)

In [24]:
recall = recall_score(y_test, y_pred, pos_label=1)
print("Recall:", recall)

Recall: 0.932475884244373

In [25]:
result = permutation_importance(
    pipe, X_test, y_test,
    n_repeats=10,
    random_state=5831,
    n_jobs=-1
)

importance = pd.DataFrame({
    "feature": X_test.columns,
    "importance": result.importances_mean
}).sort_values(by="importance", ascending=False)

print(importance.head(10))

               feature  importance
0     nutriscore_grade      0.0640
2       ecoscore_grade      0.0495
1           nova_group      0.0215
9        proteins_100g      0.0206
3          energy_kcal      0.0119
4             fat_100g      0.0046
7          sugars_100g      0.0035
10           salt_100g      0.0024
5   saturated_fat_100g      0.0020
11         sodium_100g      0.0019

In [26]:
num_pipeline = Pipeline([
    ("imputer", KNNImputer(n_neighbors=5))
])

cat_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

preprocess = ColumnTransformer([
    ("num", num_pipeline, num_cols),
    ("cat", cat_pipeline, cat_cols)
])

pipe = Pipeline([
    ("preprocess", preprocess),
    ("xgb", XGBClassifier(
        n_estimators=200,
        max_depth=4,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        random_state=5831,
        eval_metric="logloss"
    ))
])

In [27]:
pipe.fit(X_train, y_train)
y_pred = pipe.predict(X_test)

In [28]:
recall = recall_score(y_test, y_pred, pos_label=1)
print("Recall:", recall)

Recall: 0.9308681672025724

In [29]:
result = permutation_importance(
    pipe, X_test, y_test,
    n_repeats=10,
    random_state=5831,
    n_jobs=-1
)

importance = pd.DataFrame({
    "feature": X_test.columns,
    "importance": result.importances_mean
}).sort_values(by="importance", ascending=False)

print(importance.head(10))

               feature  importance
9        proteins_100g      0.1446
4             fat_100g      0.0482
7          sugars_100g      0.0473
3          energy_kcal      0.0408
6           carbs_100g      0.0369
10           salt_100g      0.0358
2       ecoscore_grade      0.0315
5   saturated_fat_100g      0.0315
8           fiber_100g      0.0290
11         sodium_100g      0.0246

In [30]:
num_pipeline = Pipeline([
    ("imputer", KNNImputer(n_neighbors=5))
])

cat_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

preprocess = ColumnTransformer([
    ("num", num_pipeline, num_cols),
    ("cat", cat_pipeline, cat_cols)
])

pipe = Pipeline([
    ("preprocess", preprocess),
    ("lgbm", LGBMClassifier(
        n_estimators=200,
        learning_rate=0.05,
        num_leaves=31,
        subsample=0.8,
        colsample_bytree=0.8,
        random_state=5831
    ))
])

In [31]:
pipe.fit(X_train, y_train)
y_pred = pipe.predict(X_test)

[LightGBM] [Info] Number of positive: 2484, number of negative: 1513
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000386 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2304
[LightGBM] [Info] Number of data points in the train set: 3997, number of used features: 29
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.621466 -> initscore=0.495776
[LightGBM] [Info] Start training from score 0.495776

/opt/anaconda3/envs/CS5831FinalClassification/lib/python3.12/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

In [32]:
recall = recall_score(y_test, y_pred, pos_label=1)
print("Recall:", recall)

Recall: 0.9244372990353698

In [32]:
with warnings.catch_warnings():
    warnings.simplefilter("ignore")

    result = permutation_importance(
    pipe, X_test, y_test,
    n_repeats=10,
    random_state=5831,
    n_jobs=-1
    )

    importance = pd.DataFrame({
    "feature": X_test.columns,
    "importance": result.importances_mean
    }).sort_values(by="importance", ascending=False)

    print(importance.head(10))

               feature  importance
9        proteins_100g      0.1626
4             fat_100g      0.0579
7          sugars_100g      0.0494
3          energy_kcal      0.0476
6           carbs_100g      0.0370
5   saturated_fat_100g      0.0367
10           salt_100g      0.0356
2       ecoscore_grade      0.0326
8           fiber_100g      0.0313
11         sodium_100g      0.0269

In [41]:
results = []

for n_d in [16, 32, 64]:
    for n_steps in [3, 5, 7]:
        for lr in [0.01, 0.02, 0.05]:
            model = TabNetClassifier(
                seed=5831,
                n_d=n_d,
                n_a=n_d,
                n_steps=n_steps,
                gamma=1.5,
                lambda_sparse=1e-4,
                optimizer_params=dict(lr=lr),
                mask_type="entmax"
            )

            model.fit(
                X_train_sub_trans,
                y_train_sub_np,
                eval_set=[(X_valid_trans, y_valid_np)],
                eval_name=["valid"],
                eval_metric=["auc"],
                max_epochs=200,
                patience=20,
                batch_size=256,
                virtual_batch_size=64,
                num_workers=0,
                drop_last=False
            )

            y_valid_prob = model.predict_proba(X_valid_trans)[:, 1]

            best_recall = -1
            best_t = None

            for t in [0.10, 0.15, 0.20, 0.25, 0.30, 0.35, 0.40, 0.45, 0.50]:
                y_valid_pred_t = (y_valid_prob >= t).astype(int)
                score = recall_score(y_valid, y_valid_pred_t, pos_label=1)

                if score > best_recall:
                    best_recall = score
                    best_t = t

            results.append({
                "n_d": n_d,
                "n_steps": n_steps,
                "lr": lr,
                "best_threshold": best_t,
                "valid_pos_recall": best_recall
            })

results_df = pd.DataFrame(results).sort_values("valid_pos_recall", ascending=False)
print(results_df.head(10))

/opt/anaconda3/envs/CS5831FinalClassification/lib/python3.12/site-packages/pytorch_tabnet/abstract_model.py:82: UserWarning: Device used : cpu
  warnings.warn(f"Device used : {self.device}")

epoch 0  | loss: 0.72676 | valid_auc: 0.6651  |  0:00:00s
epoch 1  | loss: 0.59138 | valid_auc: 0.69843 |  0:00:00s
epoch 2  | loss: 0.54902 | valid_auc: 0.73085 |  0:00:00s
epoch 3  | loss: 0.52586 | valid_auc: 0.74296 |  0:00:01s
epoch 4  | loss: 0.50635 | valid_auc: 0.75932 |  0:00:01s
epoch 5  | loss: 0.4915  | valid_auc: 0.75793 |  0:00:01s
epoch 6  | loss: 0.48501 | valid_auc: 0.77495 |  0:00:02s
epoch 7  | loss: 0.48032 | valid_auc: 0.78387 |  0:00:02s
epoch 8  | loss: 0.47285 | valid_auc: 0.78941 |  0:00:02s
epoch 9  | loss: 0.46182 | valid_auc: 0.7927  |  0:00:02s
epoch 10 | loss: 0.46286 | valid_auc: 0.79399 |  0:00:03s
epoch 11 | loss: 0.45393 | valid_auc: 0.79873 |  0:00:03s
epoch 12 | loss: 0.45033 | valid_auc: 0.80524 |  0:00:03s
epoch 13 | loss: 0.44073 | valid_auc: 0.80584 |  0:00:04s
epoch 14 | loss: 0.45177 | valid_auc: 0.80975 |  0:00:04s
epoch 15 | loss: 0.43759 | valid_auc: 0.81762 |  0:00:04s
epoch 16 | loss: 0.43901 | valid_auc: 0.81851 |  0:00:05s
epoch 17 | loss: 0.43054 | valid_auc: 0.82326 |  0:00:05s
epoch 18 | loss: 0.41078 | valid_auc: 0.82614 |  0:00:05s
epoch 19 | loss: 0.42176 | valid_auc: 0.82601 |  0:00:06s
epoch 20 | loss: 0.43022 | valid_auc: 0.82462 |  0:00:06s
epoch 21 | loss: 0.42572 | valid_auc: 0.81798 |  0:00:06s
epoch 22 | loss: 0.41613 | valid_auc: 0.83191 |  0:00:06s
epoch 23 | loss: 0.40156 | valid_auc: 0.82721 |  0:00:07s
epoch 24 | loss: 0.39877 | valid_auc: 0.81754 |  0:00:07s
epoch 25 | loss: 0.41605 | valid_auc: 0.81624 |  0:00:07s
epoch 26 | loss: 0.41413 | valid_auc: 0.82002 |  0:00:08s
epoch 27 | loss: 0.41474 | valid_auc: 0.81035 |  0:00:08s
epoch 28 | loss: 0.39322 | valid_auc: 0.81783 |  0:00:08s
epoch 29 | loss: 0.38965 | valid_auc: 0.80781 |  0:00:08s
epoch 30 | loss: 0.38198 | valid_auc: 0.81952 |  0:00:09s
epoch 31 | loss: 0.3857  | valid_auc: 0.82033 |  0:00:09s
epoch 32 | loss: 0.38783 | valid_auc: 0.81091 |  0:00:09s
epoch 33 | loss: 0.37371 | valid_auc: 0.81048 |  0:00:10s
epoch 34 | loss: 0.37801 | valid_auc: 0.80994 |  0:00:10s
epoch 35 | loss: 0.37172 | valid_auc: 0.8172  |  0:00:10s
epoch 36 | loss: 0.37583 | valid_auc: 0.83639 |  0:00:10s
epoch 37 | loss: 0.36721 | valid_auc: 0.83042 |  0:00:11s
epoch 38 | loss: 0.35976 | valid_auc: 0.83576 |  0:00:11s
epoch 39 | loss: 0.37197 | valid_auc: 0.82934 |  0:00:11s
epoch 40 | loss: 0.35986 | valid_auc: 0.80905 |  0:00:12s
epoch 41 | loss: 0.37258 | valid_auc: 0.8267  |  0:00:12s
epoch 42 | loss: 0.36703 | valid_auc: 0.83876 |  0:00:12s
epoch 43 | loss: 0.35723 | valid_auc: 0.84519 |  0:00:13s
epoch 44 | loss: 0.37431 | valid_auc: 0.82739 |  0:00:13s
epoch 45 | loss: 0.34844 | valid_auc: 0.8227  |  0:00:13s
epoch 46 | loss: 0.35212 | valid_auc: 0.8199  |  0:00:13s
epoch 47 | loss: 0.3523  | valid_auc: 0.83093 |  0:00:14s
epoch 48 | loss: 0.34826 | valid_auc: 0.81413 |  0:00:14s
epoch 49 | loss: 0.35343 | valid_auc: 0.81842 |  0:00:14s
epoch 50 | loss: 0.35325 | valid_auc: 0.82053 |  0:00:15s
epoch 51 | loss: 0.34131 | valid_auc: 0.81432 |  0:00:15s
epoch 52 | loss: 0.33431 | valid_auc: 0.82451 |  0:00:15s
epoch 53 | loss: 0.34106 | valid_auc: 0.8296  |  0:00:15s
epoch 54 | loss: 0.34829 | valid_auc: 0.8249  |  0:00:16s
epoch 55 | loss: 0.34122 | valid_auc: 0.8315  |  0:00:16s
epoch 56 | loss: 0.3411  | valid_auc: 0.82798 |  0:00:16s
epoch 57 | loss: 0.33101 | valid_auc: 0.82962 |  0:00:17s
epoch 58 | loss: 0.33298 | valid_auc: 0.83917 |  0:00:17s
epoch 59 | loss: 0.33554 | valid_auc: 0.82648 |  0:00:17s
epoch 60 | loss: 0.34845 | valid_auc: 0.83145 |  0:00:18s
epoch 61 | loss: 0.33948 | valid_auc: 0.8261  |  0:00:18s
epoch 62 | loss: 0.32429 | valid_auc: 0.82452 |  0:00:18s
epoch 63 | loss: 0.32912 | valid_auc: 0.82992 |  0:00:19s

Early stopping occurred at epoch 63 with best_epoch = 43 and best_valid_auc = 0.84519

/opt/anaconda3/envs/CS5831FinalClassification/lib/python3.12/site-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)
/opt/anaconda3/envs/CS5831FinalClassification/lib/python3.12/site-packages/pytorch_tabnet/abstract_model.py:82: UserWarning: Device used : cpu
  warnings.warn(f"Device used : {self.device}")

epoch 0  | loss: 0.70976 | valid_auc: 0.64712 |  0:00:00s
epoch 1  | loss: 0.60062 | valid_auc: 0.71919 |  0:00:00s
epoch 2  | loss: 0.5469  | valid_auc: 0.73184 |  0:00:01s
epoch 3  | loss: 0.51922 | valid_auc: 0.76323 |  0:00:01s
epoch 4  | loss: 0.50468 | valid_auc: 0.76796 |  0:00:01s
epoch 5  | loss: 0.50108 | valid_auc: 0.77866 |  0:00:02s
epoch 6  | loss: 0.4978  | valid_auc: 0.78391 |  0:00:02s
epoch 7  | loss: 0.47931 | valid_auc: 0.79912 |  0:00:02s
epoch 8  | loss: 0.47412 | valid_auc: 0.80503 |  0:00:02s
epoch 9  | loss: 0.46495 | valid_auc: 0.8146  |  0:00:03s
epoch 10 | loss: 0.45987 | valid_auc: 0.82166 |  0:00:03s
epoch 11 | loss: 0.44156 | valid_auc: 0.82368 |  0:00:03s
epoch 12 | loss: 0.44181 | valid_auc: 0.81905 |  0:00:04s
epoch 13 | loss: 0.43428 | valid_auc: 0.81649 |  0:00:04s
epoch 14 | loss: 0.43956 | valid_auc: 0.81735 |  0:00:05s
epoch 15 | loss: 0.43855 | valid_auc: 0.81275 |  0:00:05s
epoch 16 | loss: 0.4184  | valid_auc: 0.81708 |  0:00:05s
epoch 17 | loss: 0.41116 | valid_auc: 0.82282 |  0:00:06s
epoch 18 | loss: 0.41131 | valid_auc: 0.82494 |  0:00:06s
epoch 19 | loss: 0.42219 | valid_auc: 0.81824 |  0:00:06s
epoch 20 | loss: 0.41455 | valid_auc: 0.81389 |  0:00:07s
epoch 21 | loss: 0.40022 | valid_auc: 0.82913 |  0:00:07s
epoch 22 | loss: 0.40503 | valid_auc: 0.82486 |  0:00:07s
epoch 23 | loss: 0.39707 | valid_auc: 0.82891 |  0:00:08s
epoch 24 | loss: 0.39988 | valid_auc: 0.82089 |  0:00:08s
epoch 25 | loss: 0.4109  | valid_auc: 0.82601 |  0:00:08s
epoch 26 | loss: 0.41148 | valid_auc: 0.80011 |  0:00:09s
epoch 27 | loss: 0.4042  | valid_auc: 0.80814 |  0:00:09s
epoch 28 | loss: 0.40212 | valid_auc: 0.83704 |  0:00:09s
epoch 29 | loss: 0.39453 | valid_auc: 0.83491 |  0:00:10s
epoch 30 | loss: 0.38718 | valid_auc: 0.83152 |  0:00:10s
epoch 31 | loss: 0.38064 | valid_auc: 0.83257 |  0:00:10s
epoch 32 | loss: 0.39182 | valid_auc: 0.83611 |  0:00:11s
epoch 33 | loss: 0.37903 | valid_auc: 0.82645 |  0:00:11s
epoch 34 | loss: 0.38978 | valid_auc: 0.83704 |  0:00:11s
epoch 35 | loss: 0.37568 | valid_auc: 0.81604 |  0:00:12s
epoch 36 | loss: 0.3741  | valid_auc: 0.82456 |  0:00:12s
epoch 37 | loss: 0.3768  | valid_auc: 0.82402 |  0:00:12s
epoch 38 | loss: 0.3764  | valid_auc: 0.82798 |  0:00:13s
epoch 39 | loss: 0.39487 | valid_auc: 0.81346 |  0:00:13s
epoch 40 | loss: 0.38837 | valid_auc: 0.80753 |  0:00:13s
epoch 41 | loss: 0.37923 | valid_auc: 0.81949 |  0:00:13s
epoch 42 | loss: 0.37258 | valid_auc: 0.81539 |  0:00:14s
epoch 43 | loss: 0.37568 | valid_auc: 0.81936 |  0:00:14s
epoch 44 | loss: 0.36521 | valid_auc: 0.82356 |  0:00:14s
epoch 45 | loss: 0.3602  | valid_auc: 0.82719 |  0:00:15s
epoch 46 | loss: 0.36337 | valid_auc: 0.81453 |  0:00:15s
epoch 47 | loss: 0.37061 | valid_auc: 0.82958 |  0:00:15s
epoch 48 | loss: 0.36699 | valid_auc: 0.82947 |  0:00:16s
epoch 49 | loss: 0.367   | valid_auc: 0.83381 |  0:00:16s
epoch 50 | loss: 0.36074 | valid_auc: 0.82229 |  0:00:16s
epoch 51 | loss: 0.3516  | valid_auc: 0.82532 |  0:00:17s
epoch 52 | loss: 0.35163 | valid_auc: 0.81967 |  0:00:17s
epoch 53 | loss: 0.37381 | valid_auc: 0.81819 |  0:00:17s
epoch 54 | loss: 0.37194 | valid_auc: 0.82596 |  0:00:17s

Early stopping occurred at epoch 54 with best_epoch = 34 and best_valid_auc = 0.83704

/opt/anaconda3/envs/CS5831FinalClassification/lib/python3.12/site-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)
/opt/anaconda3/envs/CS5831FinalClassification/lib/python3.12/site-packages/pytorch_tabnet/abstract_model.py:82: UserWarning: Device used : cpu
  warnings.warn(f"Device used : {self.device}")

epoch 0  | loss: 0.66443 | valid_auc: 0.57935 |  0:00:00s
epoch 1  | loss: 0.59159 | valid_auc: 0.68555 |  0:00:00s
epoch 2  | loss: 0.56196 | valid_auc: 0.74407 |  0:00:00s
epoch 3  | loss: 0.53876 | valid_auc: 0.75206 |  0:00:01s
epoch 4  | loss: 0.52014 | valid_auc: 0.74699 |  0:00:01s
epoch 5  | loss: 0.50031 | valid_auc: 0.77597 |  0:00:01s
epoch 6  | loss: 0.49103 | valid_auc: 0.79413 |  0:00:02s
epoch 7  | loss: 0.47586 | valid_auc: 0.80473 |  0:00:02s
epoch 8  | loss: 0.46772 | valid_auc: 0.80019 |  0:00:03s
epoch 9  | loss: 0.45191 | valid_auc: 0.82065 |  0:00:03s
epoch 10 | loss: 0.45291 | valid_auc: 0.79147 |  0:00:03s
epoch 11 | loss: 0.44374 | valid_auc: 0.82446 |  0:00:04s
epoch 12 | loss: 0.43977 | valid_auc: 0.82292 |  0:00:04s
epoch 13 | loss: 0.42444 | valid_auc: 0.83045 |  0:00:04s
epoch 14 | loss: 0.42581 | valid_auc: 0.83751 |  0:00:05s
epoch 15 | loss: 0.43925 | valid_auc: 0.81809 |  0:00:05s
epoch 16 | loss: 0.43084 | valid_auc: 0.8264  |  0:00:05s
epoch 17 | loss: 0.44919 | valid_auc: 0.80547 |  0:00:06s
epoch 18 | loss: 0.42451 | valid_auc: 0.79901 |  0:00:06s
epoch 19 | loss: 0.41218 | valid_auc: 0.83523 |  0:00:06s
epoch 20 | loss: 0.41934 | valid_auc: 0.82617 |  0:00:07s
epoch 21 | loss: 0.40334 | valid_auc: 0.81106 |  0:00:07s
epoch 22 | loss: 0.40412 | valid_auc: 0.83136 |  0:00:07s
epoch 23 | loss: 0.41918 | valid_auc: 0.83988 |  0:00:07s
epoch 24 | loss: 0.40861 | valid_auc: 0.84524 |  0:00:08s
epoch 25 | loss: 0.39998 | valid_auc: 0.82339 |  0:00:08s
epoch 26 | loss: 0.3958  | valid_auc: 0.80638 |  0:00:08s
epoch 27 | loss: 0.40037 | valid_auc: 0.81388 |  0:00:09s
epoch 28 | loss: 0.38836 | valid_auc: 0.84131 |  0:00:09s
epoch 29 | loss: 0.37754 | valid_auc: 0.83827 |  0:00:09s
epoch 30 | loss: 0.38237 | valid_auc: 0.83341 |  0:00:10s
epoch 31 | loss: 0.38641 | valid_auc: 0.83866 |  0:00:10s
epoch 32 | loss: 0.38653 | valid_auc: 0.82311 |  0:00:10s
epoch 33 | loss: 0.37682 | valid_auc: 0.82923 |  0:00:10s
epoch 34 | loss: 0.37838 | valid_auc: 0.83657 |  0:00:11s
epoch 35 | loss: 0.37878 | valid_auc: 0.83715 |  0:00:11s
epoch 36 | loss: 0.3618  | valid_auc: 0.84504 |  0:00:11s
epoch 37 | loss: 0.36021 | valid_auc: 0.83884 |  0:00:12s
epoch 38 | loss: 0.3471  | valid_auc: 0.84415 |  0:00:12s
epoch 39 | loss: 0.3538  | valid_auc: 0.8096  |  0:00:13s
epoch 40 | loss: 0.36638 | valid_auc: 0.82771 |  0:00:13s
epoch 41 | loss: 0.37477 | valid_auc: 0.818   |  0:00:13s
epoch 42 | loss: 0.36018 | valid_auc: 0.85132 |  0:00:14s
epoch 43 | loss: 0.34328 | valid_auc: 0.83107 |  0:00:14s
epoch 44 | loss: 0.34483 | valid_auc: 0.83589 |  0:00:14s
epoch 45 | loss: 0.33382 | valid_auc: 0.84218 |  0:00:15s
epoch 46 | loss: 0.32825 | valid_auc: 0.83668 |  0:00:15s
epoch 47 | loss: 0.33722 | valid_auc: 0.86008 |  0:00:15s
epoch 48 | loss: 0.33148 | valid_auc: 0.84183 |  0:00:16s
epoch 49 | loss: 0.33389 | valid_auc: 0.83268 |  0:00:16s
epoch 50 | loss: 0.327   | valid_auc: 0.83324 |  0:00:16s
epoch 51 | loss: 0.32408 | valid_auc: 0.84741 |  0:00:17s
epoch 52 | loss: 0.33489 | valid_auc: 0.83947 |  0:00:17s
epoch 53 | loss: 0.3182  | valid_auc: 0.8302  |  0:00:17s
epoch 54 | loss: 0.31978 | valid_auc: 0.84346 |  0:00:18s
epoch 55 | loss: 0.31148 | valid_auc: 0.82858 |  0:00:18s
epoch 56 | loss: 0.33012 | valid_auc: 0.84636 |  0:00:18s
epoch 57 | loss: 0.31609 | valid_auc: 0.84238 |  0:00:19s
epoch 58 | loss: 0.31253 | valid_auc: 0.84237 |  0:00:19s
epoch 59 | loss: 0.31738 | valid_auc: 0.82887 |  0:00:19s
epoch 60 | loss: 0.33478 | valid_auc: 0.8348  |  0:00:19s
epoch 61 | loss: 0.31559 | valid_auc: 0.84261 |  0:00:20s
epoch 62 | loss: 0.31298 | valid_auc: 0.84773 |  0:00:20s
epoch 63 | loss: 0.31941 | valid_auc: 0.84433 |  0:00:20s
epoch 64 | loss: 0.30915 | valid_auc: 0.85105 |  0:00:21s
epoch 65 | loss: 0.30114 | valid_auc: 0.84617 |  0:00:21s
epoch 66 | loss: 0.2994  | valid_auc: 0.83295 |  0:00:21s
epoch 67 | loss: 0.30618 | valid_auc: 0.8437  |  0:00:22s

Early stopping occurred at epoch 67 with best_epoch = 47 and best_valid_auc = 0.86008

/opt/anaconda3/envs/CS5831FinalClassification/lib/python3.12/site-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)
/opt/anaconda3/envs/CS5831FinalClassification/lib/python3.12/site-packages/pytorch_tabnet/abstract_model.py:82: UserWarning: Device used : cpu
  warnings.warn(f"Device used : {self.device}")

epoch 0  | loss: 0.87686 | valid_auc: 0.59478 |  0:00:00s
epoch 1  | loss: 0.70337 | valid_auc: 0.63815 |  0:00:00s
epoch 2  | loss: 0.64226 | valid_auc: 0.67799 |  0:00:01s
epoch 3  | loss: 0.60372 | valid_auc: 0.68152 |  0:00:01s
epoch 4  | loss: 0.5889  | valid_auc: 0.71347 |  0:00:02s
epoch 5  | loss: 0.56754 | valid_auc: 0.69365 |  0:00:02s
epoch 6  | loss: 0.58023 | valid_auc: 0.7074  |  0:00:03s
epoch 7  | loss: 0.5459  | valid_auc: 0.74147 |  0:00:03s
epoch 8  | loss: 0.52816 | valid_auc: 0.73949 |  0:00:04s
epoch 9  | loss: 0.52162 | valid_auc: 0.75511 |  0:00:04s
epoch 10 | loss: 0.51748 | valid_auc: 0.75843 |  0:00:05s
epoch 11 | loss: 0.52089 | valid_auc: 0.75696 |  0:00:05s
epoch 12 | loss: 0.49746 | valid_auc: 0.75943 |  0:00:06s
epoch 13 | loss: 0.49586 | valid_auc: 0.78365 |  0:00:06s
epoch 14 | loss: 0.50231 | valid_auc: 0.78556 |  0:00:07s
epoch 15 | loss: 0.5048  | valid_auc: 0.78968 |  0:00:07s
epoch 16 | loss: 0.50116 | valid_auc: 0.78394 |  0:00:08s
epoch 17 | loss: 0.48385 | valid_auc: 0.79941 |  0:00:08s
epoch 18 | loss: 0.48792 | valid_auc: 0.80757 |  0:00:09s
epoch 19 | loss: 0.48484 | valid_auc: 0.80195 |  0:00:09s
epoch 20 | loss: 0.47076 | valid_auc: 0.81379 |  0:00:10s
epoch 21 | loss: 0.4771  | valid_auc: 0.79873 |  0:00:10s
epoch 22 | loss: 0.46815 | valid_auc: 0.79693 |  0:00:11s
epoch 23 | loss: 0.46631 | valid_auc: 0.79815 |  0:00:11s
epoch 24 | loss: 0.4647  | valid_auc: 0.79988 |  0:00:12s
epoch 25 | loss: 0.45326 | valid_auc: 0.80739 |  0:00:12s
epoch 26 | loss: 0.46954 | valid_auc: 0.80787 |  0:00:13s
epoch 27 | loss: 0.45163 | valid_auc: 0.8154  |  0:00:13s
epoch 28 | loss: 0.45831 | valid_auc: 0.80646 |  0:00:14s
epoch 29 | loss: 0.44865 | valid_auc: 0.80484 |  0:00:14s
epoch 30 | loss: 0.45515 | valid_auc: 0.81166 |  0:00:15s
epoch 31 | loss: 0.44653 | valid_auc: 0.80215 |  0:00:15s
epoch 32 | loss: 0.43795 | valid_auc: 0.80405 |  0:00:15s
epoch 33 | loss: 0.44403 | valid_auc: 0.8005  |  0:00:16s
epoch 34 | loss: 0.43864 | valid_auc: 0.79835 |  0:00:16s
epoch 35 | loss: 0.44372 | valid_auc: 0.80369 |  0:00:17s
epoch 36 | loss: 0.44399 | valid_auc: 0.79846 |  0:00:17s
epoch 37 | loss: 0.43404 | valid_auc: 0.80803 |  0:00:18s
epoch 38 | loss: 0.43225 | valid_auc: 0.80806 |  0:00:18s
epoch 39 | loss: 0.4326  | valid_auc: 0.82539 |  0:00:19s
epoch 40 | loss: 0.43483 | valid_auc: 0.82077 |  0:00:19s
epoch 41 | loss: 0.4467  | valid_auc: 0.79832 |  0:00:20s
epoch 42 | loss: 0.44194 | valid_auc: 0.81138 |  0:00:20s
epoch 43 | loss: 0.43997 | valid_auc: 0.80729 |  0:00:21s
epoch 44 | loss: 0.44892 | valid_auc: 0.80541 |  0:00:21s
epoch 45 | loss: 0.44397 | valid_auc: 0.79749 |  0:00:22s
epoch 46 | loss: 0.43433 | valid_auc: 0.80873 |  0:00:22s
epoch 47 | loss: 0.44388 | valid_auc: 0.81449 |  0:00:23s
epoch 48 | loss: 0.43705 | valid_auc: 0.81391 |  0:00:23s
epoch 49 | loss: 0.43302 | valid_auc: 0.81322 |  0:00:24s
epoch 50 | loss: 0.43163 | valid_auc: 0.82096 |  0:00:24s
epoch 51 | loss: 0.43129 | valid_auc: 0.81517 |  0:00:24s
epoch 52 | loss: 0.42398 | valid_auc: 0.80856 |  0:00:25s
epoch 53 | loss: 0.42752 | valid_auc: 0.81591 |  0:00:25s
epoch 54 | loss: 0.41803 | valid_auc: 0.82477 |  0:00:26s
epoch 55 | loss: 0.42195 | valid_auc: 0.82479 |  0:00:26s
epoch 56 | loss: 0.42047 | valid_auc: 0.82684 |  0:00:27s
epoch 57 | loss: 0.41508 | valid_auc: 0.82158 |  0:00:27s
epoch 58 | loss: 0.41262 | valid_auc: 0.81446 |  0:00:28s
epoch 59 | loss: 0.41265 | valid_auc: 0.81929 |  0:00:28s
epoch 60 | loss: 0.4193  | valid_auc: 0.81979 |  0:00:29s
epoch 61 | loss: 0.41692 | valid_auc: 0.82288 |  0:00:29s
epoch 62 | loss: 0.42111 | valid_auc: 0.81719 |  0:00:30s
epoch 63 | loss: 0.42259 | valid_auc: 0.81805 |  0:00:30s
epoch 64 | loss: 0.41205 | valid_auc: 0.81988 |  0:00:31s
epoch 65 | loss: 0.40915 | valid_auc: 0.82668 |  0:00:31s
epoch 66 | loss: 0.41307 | valid_auc: 0.81621 |  0:00:32s
epoch 67 | loss: 0.41567 | valid_auc: 0.82099 |  0:00:32s
epoch 68 | loss: 0.41849 | valid_auc: 0.81921 |  0:00:33s
epoch 69 | loss: 0.40023 | valid_auc: 0.81851 |  0:00:33s
epoch 70 | loss: 0.40768 | valid_auc: 0.81702 |  0:00:33s
epoch 71 | loss: 0.40854 | valid_auc: 0.82403 |  0:00:34s
epoch 72 | loss: 0.40552 | valid_auc: 0.81715 |  0:00:34s
epoch 73 | loss: 0.40826 | valid_auc: 0.82745 |  0:00:35s
epoch 74 | loss: 0.40434 | valid_auc: 0.83518 |  0:00:35s
epoch 75 | loss: 0.39031 | valid_auc: 0.8251  |  0:00:36s
epoch 76 | loss: 0.3945  | valid_auc: 0.82338 |  0:00:36s
epoch 77 | loss: 0.4042  | valid_auc: 0.82357 |  0:00:37s
epoch 78 | loss: 0.40005 | valid_auc: 0.82956 |  0:00:38s
epoch 79 | loss: 0.39262 | valid_auc: 0.81931 |  0:00:38s
epoch 80 | loss: 0.40344 | valid_auc: 0.81197 |  0:00:39s
epoch 81 | loss: 0.38873 | valid_auc: 0.81571 |  0:00:39s
epoch 82 | loss: 0.39941 | valid_auc: 0.81653 |  0:00:40s
epoch 83 | loss: 0.39146 | valid_auc: 0.805   |  0:00:40s
epoch 84 | loss: 0.3882  | valid_auc: 0.80569 |  0:00:41s
epoch 85 | loss: 0.38339 | valid_auc: 0.81413 |  0:00:41s
epoch 86 | loss: 0.39005 | valid_auc: 0.79924 |  0:00:42s
epoch 87 | loss: 0.39588 | valid_auc: 0.80193 |  0:00:43s
epoch 88 | loss: 0.38812 | valid_auc: 0.80924 |  0:00:43s
epoch 89 | loss: 0.39688 | valid_auc: 0.81942 |  0:00:44s
epoch 90 | loss: 0.38666 | valid_auc: 0.82289 |  0:00:44s
epoch 91 | loss: 0.40053 | valid_auc: 0.82034 |  0:00:45s
epoch 92 | loss: 0.38724 | valid_auc: 0.81636 |  0:00:45s
epoch 93 | loss: 0.38179 | valid_auc: 0.82121 |  0:00:46s
epoch 94 | loss: 0.38444 | valid_auc: 0.82236 |  0:00:46s

Early stopping occurred at epoch 94 with best_epoch = 74 and best_valid_auc = 0.83518

/opt/anaconda3/envs/CS5831FinalClassification/lib/python3.12/site-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)
/opt/anaconda3/envs/CS5831FinalClassification/lib/python3.12/site-packages/pytorch_tabnet/abstract_model.py:82: UserWarning: Device used : cpu
  warnings.warn(f"Device used : {self.device}")

epoch 0  | loss: 0.81985 | valid_auc: 0.58661 |  0:00:00s
epoch 1  | loss: 0.65451 | valid_auc: 0.66653 |  0:00:01s
epoch 2  | loss: 0.63713 | valid_auc: 0.69709 |  0:00:01s
epoch 3  | loss: 0.60607 | valid_auc: 0.72236 |  0:00:01s
epoch 4  | loss: 0.57886 | valid_auc: 0.71739 |  0:00:02s
epoch 5  | loss: 0.55579 | valid_auc: 0.72793 |  0:00:02s
epoch 6  | loss: 0.53437 | valid_auc: 0.7374  |  0:00:03s
epoch 7  | loss: 0.52363 | valid_auc: 0.76447 |  0:00:03s
epoch 8  | loss: 0.5165  | valid_auc: 0.72832 |  0:00:04s
epoch 9  | loss: 0.51409 | valid_auc: 0.72787 |  0:00:04s
epoch 10 | loss: 0.52719 | valid_auc: 0.72229 |  0:00:05s
epoch 11 | loss: 0.52549 | valid_auc: 0.73554 |  0:00:05s
epoch 12 | loss: 0.51677 | valid_auc: 0.73629 |  0:00:06s
epoch 13 | loss: 0.50391 | valid_auc: 0.73811 |  0:00:06s
epoch 14 | loss: 0.49794 | valid_auc: 0.7473  |  0:00:07s
epoch 15 | loss: 0.49503 | valid_auc: 0.74882 |  0:00:07s
epoch 16 | loss: 0.49451 | valid_auc: 0.74962 |  0:00:08s
epoch 17 | loss: 0.49352 | valid_auc: 0.75966 |  0:00:08s
epoch 18 | loss: 0.50754 | valid_auc: 0.77864 |  0:00:09s
epoch 19 | loss: 0.49328 | valid_auc: 0.77219 |  0:00:09s
epoch 20 | loss: 0.48418 | valid_auc: 0.78856 |  0:00:10s
epoch 21 | loss: 0.48975 | valid_auc: 0.75824 |  0:00:10s
epoch 22 | loss: 0.49503 | valid_auc: 0.7641  |  0:00:11s
epoch 23 | loss: 0.4895  | valid_auc: 0.76989 |  0:00:11s
epoch 24 | loss: 0.47848 | valid_auc: 0.75157 |  0:00:11s
epoch 25 | loss: 0.46618 | valid_auc: 0.76834 |  0:00:12s
epoch 26 | loss: 0.47738 | valid_auc: 0.75955 |  0:00:12s
epoch 27 | loss: 0.46623 | valid_auc: 0.76514 |  0:00:13s
epoch 28 | loss: 0.47839 | valid_auc: 0.75522 |  0:00:13s
epoch 29 | loss: 0.45842 | valid_auc: 0.76329 |  0:00:14s
epoch 30 | loss: 0.466   | valid_auc: 0.78072 |  0:00:14s
epoch 31 | loss: 0.46353 | valid_auc: 0.76259 |  0:00:15s
epoch 32 | loss: 0.44824 | valid_auc: 0.76615 |  0:00:15s
epoch 33 | loss: 0.45626 | valid_auc: 0.76851 |  0:00:16s
epoch 34 | loss: 0.45203 | valid_auc: 0.76514 |  0:00:16s
epoch 35 | loss: 0.45849 | valid_auc: 0.7761  |  0:00:17s
epoch 36 | loss: 0.44705 | valid_auc: 0.76969 |  0:00:17s
epoch 37 | loss: 0.4527  | valid_auc: 0.78681 |  0:00:18s
epoch 38 | loss: 0.45148 | valid_auc: 0.78066 |  0:00:18s
epoch 39 | loss: 0.45668 | valid_auc: 0.77204 |  0:00:19s
epoch 40 | loss: 0.44724 | valid_auc: 0.78194 |  0:00:19s

Early stopping occurred at epoch 40 with best_epoch = 20 and best_valid_auc = 0.78856

/opt/anaconda3/envs/CS5831FinalClassification/lib/python3.12/site-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)
/opt/anaconda3/envs/CS5831FinalClassification/lib/python3.12/site-packages/pytorch_tabnet/abstract_model.py:82: UserWarning: Device used : cpu
  warnings.warn(f"Device used : {self.device}")

epoch 0  | loss: 0.77211 | valid_auc: 0.59814 |  0:00:00s
epoch 1  | loss: 0.60362 | valid_auc: 0.6939  |  0:00:00s
epoch 2  | loss: 0.58055 | valid_auc: 0.6895  |  0:00:01s
epoch 3  | loss: 0.55737 | valid_auc: 0.69383 |  0:00:01s
epoch 4  | loss: 0.55631 | valid_auc: 0.68583 |  0:00:02s
epoch 5  | loss: 0.54035 | valid_auc: 0.71251 |  0:00:02s
epoch 6  | loss: 0.53274 | valid_auc: 0.73674 |  0:00:03s
epoch 7  | loss: 0.51819 | valid_auc: 0.76843 |  0:00:03s
epoch 8  | loss: 0.51394 | valid_auc: 0.77369 |  0:00:04s
epoch 9  | loss: 0.50687 | valid_auc: 0.76897 |  0:00:04s
epoch 10 | loss: 0.51628 | valid_auc: 0.76443 |  0:00:05s
epoch 11 | loss: 0.50622 | valid_auc: 0.7776  |  0:00:05s
epoch 12 | loss: 0.50041 | valid_auc: 0.7631  |  0:00:06s
epoch 13 | loss: 0.50997 | valid_auc: 0.77561 |  0:00:06s
epoch 14 | loss: 0.49675 | valid_auc: 0.75751 |  0:00:06s
epoch 15 | loss: 0.48819 | valid_auc: 0.76445 |  0:00:07s
epoch 16 | loss: 0.48467 | valid_auc: 0.77424 |  0:00:07s
epoch 17 | loss: 0.48718 | valid_auc: 0.79467 |  0:00:08s
epoch 18 | loss: 0.48207 | valid_auc: 0.78319 |  0:00:08s
epoch 19 | loss: 0.47642 | valid_auc: 0.77546 |  0:00:09s
epoch 20 | loss: 0.48729 | valid_auc: 0.7601  |  0:00:09s
epoch 21 | loss: 0.49163 | valid_auc: 0.79002 |  0:00:10s
epoch 22 | loss: 0.47974 | valid_auc: 0.79327 |  0:00:10s
epoch 23 | loss: 0.4804  | valid_auc: 0.78059 |  0:00:11s
epoch 24 | loss: 0.48029 | valid_auc: 0.77807 |  0:00:11s
epoch 25 | loss: 0.47633 | valid_auc: 0.79373 |  0:00:12s
epoch 26 | loss: 0.48311 | valid_auc: 0.75962 |  0:00:12s
epoch 27 | loss: 0.47584 | valid_auc: 0.77513 |  0:00:13s
epoch 28 | loss: 0.46576 | valid_auc: 0.7523  |  0:00:13s
epoch 29 | loss: 0.46421 | valid_auc: 0.74714 |  0:00:14s
epoch 30 | loss: 0.47917 | valid_auc: 0.75648 |  0:00:14s
epoch 31 | loss: 0.48973 | valid_auc: 0.78805 |  0:00:15s
epoch 32 | loss: 0.48336 | valid_auc: 0.75476 |  0:00:15s
epoch 33 | loss: 0.47361 | valid_auc: 0.7049  |  0:00:16s
epoch 34 | loss: 0.4801  | valid_auc: 0.73913 |  0:00:16s
epoch 35 | loss: 0.47506 | valid_auc: 0.6724  |  0:00:17s
epoch 36 | loss: 0.47423 | valid_auc: 0.73518 |  0:00:17s
epoch 37 | loss: 0.45789 | valid_auc: 0.74691 |  0:00:18s

Early stopping occurred at epoch 37 with best_epoch = 17 and best_valid_auc = 0.79467

/opt/anaconda3/envs/CS5831FinalClassification/lib/python3.12/site-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)
/opt/anaconda3/envs/CS5831FinalClassification/lib/python3.12/site-packages/pytorch_tabnet/abstract_model.py:82: UserWarning: Device used : cpu
  warnings.warn(f"Device used : {self.device}")

epoch 0  | loss: 0.90997 | valid_auc: 0.58057 |  0:00:00s
epoch 1  | loss: 0.67947 | valid_auc: 0.5866  |  0:00:01s
epoch 2  | loss: 0.63946 | valid_auc: 0.65811 |  0:00:02s
epoch 3  | loss: 0.61302 | valid_auc: 0.66036 |  0:00:02s
epoch 4  | loss: 0.60643 | valid_auc: 0.66794 |  0:00:03s
epoch 5  | loss: 0.58641 | valid_auc: 0.69891 |  0:00:04s
epoch 6  | loss: 0.58961 | valid_auc: 0.72152 |  0:00:04s
epoch 7  | loss: 0.57871 | valid_auc: 0.75869 |  0:00:05s
epoch 8  | loss: 0.56567 | valid_auc: 0.72763 |  0:00:06s
epoch 9  | loss: 0.56938 | valid_auc: 0.69297 |  0:00:06s
epoch 10 | loss: 0.56374 | valid_auc: 0.68767 |  0:00:07s
epoch 11 | loss: 0.56058 | valid_auc: 0.70536 |  0:00:08s
epoch 12 | loss: 0.56041 | valid_auc: 0.70535 |  0:00:08s
epoch 13 | loss: 0.55057 | valid_auc: 0.71344 |  0:00:09s
epoch 14 | loss: 0.57826 | valid_auc: 0.72722 |  0:00:09s
epoch 15 | loss: 0.55089 | valid_auc: 0.74263 |  0:00:10s
epoch 16 | loss: 0.54396 | valid_auc: 0.75663 |  0:00:11s
epoch 17 | loss: 0.56827 | valid_auc: 0.76886 |  0:00:11s
epoch 18 | loss: 0.5516  | valid_auc: 0.75894 |  0:00:12s
epoch 19 | loss: 0.52087 | valid_auc: 0.7687  |  0:00:13s
epoch 20 | loss: 0.52079 | valid_auc: 0.76882 |  0:00:13s
epoch 21 | loss: 0.52419 | valid_auc: 0.766   |  0:00:14s
epoch 22 | loss: 0.53134 | valid_auc: 0.76974 |  0:00:15s
epoch 23 | loss: 0.52041 | valid_auc: 0.75214 |  0:00:15s
epoch 24 | loss: 0.51407 | valid_auc: 0.74674 |  0:00:16s
epoch 25 | loss: 0.50881 | valid_auc: 0.72648 |  0:00:16s
epoch 26 | loss: 0.51064 | valid_auc: 0.7321  |  0:00:17s
epoch 27 | loss: 0.50997 | valid_auc: 0.70735 |  0:00:18s
epoch 28 | loss: 0.50144 | valid_auc: 0.72668 |  0:00:18s
epoch 29 | loss: 0.49285 | valid_auc: 0.74743 |  0:00:19s
epoch 30 | loss: 0.49089 | valid_auc: 0.75258 |  0:00:20s
epoch 31 | loss: 0.49352 | valid_auc: 0.75446 |  0:00:20s
epoch 32 | loss: 0.48944 | valid_auc: 0.75128 |  0:00:21s
epoch 33 | loss: 0.48051 | valid_auc: 0.73407 |  0:00:22s
epoch 34 | loss: 0.49895 | valid_auc: 0.73443 |  0:00:22s
epoch 35 | loss: 0.48828 | valid_auc: 0.76121 |  0:00:23s
epoch 36 | loss: 0.47134 | valid_auc: 0.7583  |  0:00:23s
epoch 37 | loss: 0.46555 | valid_auc: 0.77499 |  0:00:24s
epoch 38 | loss: 0.46617 | valid_auc: 0.78517 |  0:00:25s
epoch 39 | loss: 0.46334 | valid_auc: 0.7911  |  0:00:25s
epoch 40 | loss: 0.46567 | valid_auc: 0.78741 |  0:00:26s
epoch 41 | loss: 0.46032 | valid_auc: 0.79199 |  0:00:27s
epoch 42 | loss: 0.46077 | valid_auc: 0.79863 |  0:00:27s
epoch 43 | loss: 0.45191 | valid_auc: 0.77    |  0:00:28s
epoch 44 | loss: 0.45607 | valid_auc: 0.77519 |  0:00:29s
epoch 45 | loss: 0.45272 | valid_auc: 0.78402 |  0:00:29s
epoch 46 | loss: 0.45105 | valid_auc: 0.79025 |  0:00:30s
epoch 47 | loss: 0.43565 | valid_auc: 0.78977 |  0:00:31s
epoch 48 | loss: 0.43649 | valid_auc: 0.80211 |  0:00:31s
epoch 49 | loss: 0.43775 | valid_auc: 0.78407 |  0:00:32s
epoch 50 | loss: 0.43385 | valid_auc: 0.79984 |  0:00:33s
epoch 51 | loss: 0.4221  | valid_auc: 0.79418 |  0:00:33s
epoch 52 | loss: 0.42139 | valid_auc: 0.79904 |  0:00:34s
epoch 53 | loss: 0.43708 | valid_auc: 0.78059 |  0:00:34s
epoch 54 | loss: 0.42961 | valid_auc: 0.81769 |  0:00:35s
epoch 55 | loss: 0.42399 | valid_auc: 0.80882 |  0:00:36s
epoch 56 | loss: 0.4179  | valid_auc: 0.81288 |  0:00:36s
epoch 57 | loss: 0.41956 | valid_auc: 0.8234  |  0:00:37s
epoch 58 | loss: 0.40965 | valid_auc: 0.81176 |  0:00:38s
epoch 59 | loss: 0.40127 | valid_auc: 0.81075 |  0:00:38s
epoch 60 | loss: 0.41695 | valid_auc: 0.79812 |  0:00:39s
epoch 61 | loss: 0.41275 | valid_auc: 0.8102  |  0:00:40s
epoch 62 | loss: 0.42085 | valid_auc: 0.81255 |  0:00:40s
epoch 63 | loss: 0.40721 | valid_auc: 0.81869 |  0:00:41s
epoch 64 | loss: 0.39329 | valid_auc: 0.8176  |  0:00:41s
epoch 65 | loss: 0.40881 | valid_auc: 0.79978 |  0:00:42s
epoch 66 | loss: 0.40751 | valid_auc: 0.80681 |  0:00:43s
epoch 67 | loss: 0.40935 | valid_auc: 0.80858 |  0:00:43s
epoch 68 | loss: 0.39696 | valid_auc: 0.82028 |  0:00:44s
epoch 69 | loss: 0.40402 | valid_auc: 0.82348 |  0:00:45s
epoch 70 | loss: 0.3899  | valid_auc: 0.8228  |  0:00:45s
epoch 71 | loss: 0.38895 | valid_auc: 0.81139 |  0:00:46s
epoch 72 | loss: 0.39291 | valid_auc: 0.82676 |  0:00:47s
epoch 73 | loss: 0.39546 | valid_auc: 0.82842 |  0:00:47s
epoch 74 | loss: 0.40506 | valid_auc: 0.82158 |  0:00:48s
epoch 75 | loss: 0.40177 | valid_auc: 0.83644 |  0:00:49s
epoch 76 | loss: 0.39547 | valid_auc: 0.83075 |  0:00:49s
epoch 77 | loss: 0.41768 | valid_auc: 0.8206  |  0:00:50s
epoch 78 | loss: 0.39321 | valid_auc: 0.79937 |  0:00:50s
epoch 79 | loss: 0.40599 | valid_auc: 0.81139 |  0:00:51s
epoch 80 | loss: 0.40371 | valid_auc: 0.81379 |  0:00:52s
epoch 81 | loss: 0.40426 | valid_auc: 0.81838 |  0:00:52s

KeyboardInterrupt:

In [37]:
y_prob = tabnet.predict_proba(X_valid_trans)[:, 1]

for t in [0.5, 0.4, 0.3, 0.2]:
    y_pred_t = (y_prob >= t).astype(int)
    score = recall_score(y_valid, y_pred_t, pos_label=1)
    print(f"threshold={t:.2f}, positive recall={score:.4f}")

threshold=0.50, positive recall=0.9356
threshold=0.40, positive recall=0.9618
threshold=0.30, positive recall=0.9759
threshold=0.20, positive recall=0.9839